// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    403: typeof import('./views/403.vue')['default']
    404: typeof import('./views/404.vue')['default']
    App: typeof import('./App.vue')['default']
    Charts: typeof import('./views/charts.vue')['default']
    Dashboard: typeof import('./views/dashboard.vue')['default']
    Donate: typeof import('./views/donate.vue')['default']
    Editor: typeof import('./views/editor.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Form: typeof import('./views/form.vue')['default']
    Header: typeof import('./components/header.vue')['default']
    Home: typeof import('./views/home.vue')['default']
    Icon: typeof import('./views/icon.vue')['default']
    Login: typeof import('./views/login.vue')['default']
    Markdown: typeof import('./views/markdown.vue')['default']
    Permission: typeof import('./views/permission.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/sidebar.vue')['default']
    Table: typeof import('./views/table.vue')['default']
    Tabs: typeof import('./views/tabs.vue')['default']
    Tags: typeof import('./components/tags.vue')['default']
    Upload: typeof import('./views/upload.vue')['default']
    User: typeof import('./views/user.vue')['default']
  }
}
